'\" t
.\"     Title: AsciiDoc - Automatyczna dokumentacja kodu
.\"    Author: Dokumentacja kodu przy pomocy programu AsciiDoctor
.\" Generator: Asciidoctor 1.5.7.1
.\"      Date: 2018-05-18
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "ASCIIDOC \- AUTOMATYCZNA DOKUMENTACJA KODU" "1" "2018-05-18" "\ \&" "\ \&"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SS "Ubuntu"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
W terminalu wydajemy polecenie
.sp
.if n .RS 4
.nf
sudo apt\-get install asciidoctor
.fi
.if n .RE
.RE
.SH "DOKUMENTACJA"
.SS "Klasa App"
.sp
.B Metody:
.br
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Main
.sp
.if n .RS 4
.nf
    public static void main( String[] args ) \fB(1)\fP
    {
        System.out.println( "Hello World!" ); \fB(2)\fP
    }
.fi
.if n .RE
.RE
.TS
tab(:);
r lw(\n(.lu*75u/100u).
\fB(1)\fP\h'-2n':T{
Nazwa metody
T}
\fB(2)\fP\h'-2n':T{
Wypisanie na ekranie tekstu
T}
.TE
.SH "PRZETWARZANIE TREŚCI"
.SS "HTML5"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Otwórz konsole
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Przejdź do katalogu, który zawiera twój plik .adoc
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Wpisz polecenie
.sp
.if n .RS 4
.nf
asciidoctor plik.adoc
.fi
.if n .RE
.RE
.SS "XHTML5"
.sp
.if n .RS 4
.nf
asciidoctor \-b xhtml5 plik.doc
.fi
.if n .RE
.SS "DocBook"
.sp
.if n .RS 4
.nf
asciidoctor \-b docbook plik.doc
.fi
.if n .RE
.SS "Man pages"
.sp
.if n .RS 4
.nf
asciidoctor \-b manpage plik.doc
.fi
.if n .RE
.SS "PDF"
.sp
Aby przetworzyć plik .adoc do formatu pdf należy:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Zainstalować asciidoctor\-pdf
.sp
.if n .RS 4
.nf
gem install asciidoctor\-pdf \-\-pre
.fi
.if n .RE
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Wydać polecenie:
.sp
.if n .RS 4
.nf
asciidoctor\-pdf file.adoc
.fi
.if n .RE
.RE
.SH "KURS"
.sp
Pełen kurs można naleźć na stronie domowej programu \fBAsciiDoctor\fP pod adresem: \c
.URL "https://asciidoctor.org/docs/user\-manual/" "" ""
.br
Mały przykład z użyciem AsciDoctor znajduje się na repozytorium: \c
.URL "https://github.com/PrezentacjaPAM/AsciiDoc" "" ""
.SH "AUTHOR"
.sp
Dokumentacja kodu przy pomocy programu AsciiDoctor